const en = {
	title: 'Email diagnostics',
	intro:
		'A fixed diagnostic group checks current email eligibility. It does not change consent or send messages.',
	coverage:
		'A completed traversal means all declared members were visited. It does not prove continuous or historical eligibility, or delivery.',
	create: 'Declare diagnostic group',
	refresh: 'Refresh',
	more: 'More groups',
	empty: 'No diagnostic groups.',
	loading: 'Loading…',
	unavailable: 'State could not be confirmed. Refresh before continuing.',
	query: 'Find participants',
	search: 'Search',
	previous: 'Previous',
	next: 'Next',
	selected: 'Selected',
	members: 'Members',
	registrationsFrom: 'Registration from (UTC)',
	registrationsUntil: 'Registration through (UTC)',
	paymentsFrom: 'Payments from (UTC)',
	paymentsUntil: 'Payments through (UTC)',
	declare: 'Declare group',
	repeat: 'Repeat the same declaration',
	pending:
		'The declaration response is uncertain. Repeat this exact request to recover its result.',
	cancelEdit: 'The selected membership and dates are frozen while declaration is pending.',
	declared: 'Declared',
	started: 'Observation began',
	closed: 'Closed',
	legacy: 'Earlier diagnostic group',
	ready: 'Not started',
	running: 'Running',
	completed: 'All members visited',
	failed: 'Incomplete traversal',
	progress: 'Visited members',
	scenarios: 'Checked scenarios',
	missing: 'Missing sources among visited members',
	reason: 'Stop reason',
	run: 'Start or continue traversal',
	stop: 'Stop after current page',
	stopping: 'Waiting for the current page to settle…',
	close: 'Close group and retain history',
	busy: 'Another operator holds the lease. Refresh the state; continue after the lease expires.',
	conflict: 'The saved position or lease changed. Refresh the state before continuing.',
	userError: 'Could not load participants.',
	declarationError: 'The group was not declared. Check membership and date bounds.',
	unknown: 'Not yet known',
	noMatches: 'No ordinary accounts on this page.',
	exclusive: 'upper boundary excluded',
	lease: 'Lease expires',
	cap: 'Select 1–500 ordinary accounts, including accounts without consent or a verified address.'
};
const ru: typeof en = {
	title: 'Диагностика писем',
	intro:
		'Фиксированная диагностическая группа проверяет текущие условия отправки. Создание группы не меняет согласия и не отправляет письма.',
	coverage:
		'Завершённый проход означает, что проверены все заявленные участники. Он не доказывает непрерывную или прошлую готовность к отправке либо доставку.',
	create: 'Объявить диагностическую группу',
	refresh: 'Обновить',
	more: 'Ещё группы',
	empty: 'Диагностических групп пока нет.',
	loading: 'Загрузка…',
	unavailable: 'Не удалось подтвердить состояние. Обновите его перед продолжением.',
	query: 'Найти участников',
	search: 'Найти',
	previous: 'Назад',
	next: 'Далее',
	selected: 'Выбрано',
	members: 'Участников',
	registrationsFrom: 'Регистрация с (UTC)',
	registrationsUntil: 'Регистрация по (UTC)',
	paymentsFrom: 'Платежи с (UTC)',
	paymentsUntil: 'Платежи по (UTC)',
	declare: 'Объявить группу',
	repeat: 'Повторить то же объявление',
	pending:
		'Результат объявления пока неизвестен. Повторите этот же запрос, чтобы получить сохранённый результат.',
	cancelEdit: 'Пока результат объявления неизвестен, выбранные участники и даты зафиксированы.',
	declared: 'Объявлена',
	started: 'Начало наблюдения',
	closed: 'Закрыта',
	legacy: 'Прежняя диагностическая группа',
	ready: 'Не начат',
	running: 'Идёт проверка',
	completed: 'Все участники посещены',
	failed: 'Неполный проход',
	progress: 'Посещено участников',
	scenarios: 'Проверено сценариев',
	missing: 'Потерянных источников среди посещённых',
	reason: 'Причина остановки',
	run: 'Начать или продолжить проход',
	stop: 'Остановиться после текущей страницы',
	stopping: 'Ожидаем завершения текущей страницы…',
	close: 'Закрыть группу и сохранить историю',
	busy: 'Другой оператор удерживает аренду обработки. Обновите состояние; продолжение доступно после её истечения.',
	conflict: 'Сохранённая позиция или аренда изменилась. Обновите состояние перед продолжением.',
	userError: 'Не удалось загрузить участников.',
	declarationError: 'Группа не объявлена. Проверьте состав и границы дат.',
	unknown: 'Пока неизвестно',
	noMatches: 'На этой странице нет обычных аккаунтов.',
	exclusive: 'верхняя граница исключена',
	lease: 'Аренда до',
	cap: 'Выберите от 1 до 500 обычных аккаунтов, в том числе без согласия или подтверждённого адреса.'
};
export const emailObservationCopy = (language: string): typeof en =>
	language.startsWith('ru') ? ru : en;
