# docs/solutions frontmatter schema (lightweight)
#
# This schema is intentionally small and human-maintainable.
# Use it as a reference when creating new solution docs.

enums:
  severity:
    - critical
    - high
    - medium
    - low
  problem_type:
    - documentation
    - workflow
    - tooling
    - testing
    - configuration
    - security
    - performance
    - bugfix
    - refactor
  root_cause:
    - doc-drift
    - inconsistent-standards
    - stale-task-log
    - missing-tooling
    - unclear-process
    - upstream-sync-friction
